In [23]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("test_data.csv")
data.head()

Wt (X)  Age (Y)
0      80       27
1      53       38
2      85       73
3      83       73
4      56       28

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
lr = LinearRegression()

In [12]:
X = data[["Wt (X)"]]
y = data[["Age (Y)"]]

In [13]:
lr.fit(X,y)

LinearRegression()

In [15]:
lr.coef_

array([[0.59987244]])

In [16]:
lr.intercept_

array([11.55862655])

In [17]:
lr.predict(X)

array([[59.54842139],
       [43.35186563],
       [62.54778357],
       [61.34803869],
       [45.15148294],
       [49.35058999],
       [49.35058999],
       [46.35122781]])

In [20]:
lr.score(X,y)

0.13454748412407058

In [21]:
from sklearn.metrics import mean_squared_error

In [24]:
np.sqrt(mean_squared_error(lr.predict(X), y))

18.44498570365844